backend:
  name: git-gateway
  repo: Larissa-Ettlin/portfolio
  branch: main
  identity_url: https://auth.decapbridge.com/sites/e6222ea6-6479-40ec-822f-7a1da5ca4d90
  gateway_url: https://gateway.decapbridge.com

media_folder: "public/uploads"
public_folder: "/uploads"

media_library:
  name: uploadcare

# Optional
commit_messages:
  create: 'Create {{collection}} "{{slug}}"'
  update: 'Update {{collection}} "{{slug}}"'
  delete: 'Delete {{collection}} "{{slug}}"'
  uploadMedia: 'Upload "{{path}}"'
  deleteMedia: 'Delete "{{path}}"'

logo_url: https://decapbridge.com/decapcms-with-bridge.svg

site_url: https://Larissa-Ettlin.github.io/portfolio

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"

    fields:
  - { name: "name", label: "Project Name", widget: "string" }
  - { name: "description", label: "Description", widget: "text" }
  - { name: "date", label: "Date", widget: "datetime" }
  - { name: "cover", label: "Cover Image", widget: "image" }
  - { name: "coverAlt", label: "Cover Alt Text", widget: "string" }
  - { name: "logo", label: "Logo", widget: "image" }
  - { name: "caseStudy", label: "Case Study", widget: "boolean", default: false }
  - { name: "tags", label: "Tags", widget: "list" }
  - { name: "draft", label: "Draft", widget: "boolean", default: false }
  - { name: "body", label: "Content", widget: "markdown" }
