backend:
  name: github
  repo: Larissa-Ettlin/portfolio
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "year", label: "Year", widget: "number" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "cover", label: "Cover Image", widget: "image" }
      - { name: "draft", label: "Draft", widget: "boolean", default: false }
      - { name: "body", label: "Content", widget: "markdown" }
